name: Run Tests

on:
  push:
    paths:
      - 'src/main/java/org/cheesecakeseal/softwaretesting/SampleCalc*.java'
      - 'src/main/java/org/cheesecakeseal/softwaretesting/SampleCalcApp*.java'
      - 'src/test/java/org/cheesecakeseal/softwaretesting/SampleCalc*.java'
      - 'src/test/java/org/cheesecakeseal/softwaretesting/SampleCalcApp*.java'
  pull_request:
    paths:
      - 'src/main/java/org/cheesecakeseal/softwaretesting/SampleCalc*.java'
      - 'src/main/java/org/cheesecakeseal/softwaretesting/SampleCalcApp*.java'
      - 'src/test/java/org/cheesecakeseal/softwaretesting/SampleCalc*.java'
      - 'src/test/java/org/cheesecakeseal/softwaretesting/SampleCalcApp*.java'

jobs:
  test:
    runs-on: ubuntu-latest  # Ubuntu is standard practice as it uses up very little system resources

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and compile
        run: |
          mvn clean install -DskipTests=true

      - name: Start Application Server # Web app Tests do not work if the web app isn't running
        run: |
          nohup mvn exec:java -Dexec.mainClass="org.cheesecakeseal.softwaretesting.SampleCalcApp" > server.log 2>&1 &
          echo $! > server.pid
        env:
          SERVER_PORT: 7000

      - name: Wait for server to start
        run: |
          sleep 10 # Adjust based on server startup time

      - name: Run Tests
        run: |
          mvn test

      - name: Kill Application Server
        if: always()
        run: |
          kill $(cat server.pid)
