name: Java CI with Maven

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.java'
      - 'test/**/*.java'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**/*.java'
      - 'test/**/*.java'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Build with Maven
        run: mvn clean install -DskipTests=false

      - name: Run unit tests with Maven
        run: mvn test

      - name: Run integration tests
        run: mvn verify
