name: Run SampleCalc Tests

on:
  push:
    paths:
      - 'src/main/java/org/cheesecakeseal/softwaretesting/SampleCalc*.java'
      - 'src/test/java/org/cheesecakeseal/softwaretesting/SampleCalcApp*.java'
  pull_request:
    paths:
      - 'src/main/java/org/cheesecakeseal/softwaretesting/SampleCalc*.java'
      - 'src/test/java/org/cheesecakeseal/softwaretesting/SampleCalcApp*.java'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21.0.4'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Tests
        run: |
          mvn clean test


